<div class="row">
    <div class="col-12">
        <div class="card my-2 my-md-3">
            <div class="card-header text-center">
                Specialiteiten deze week
            </div>
            
            <div id="carouselExampleControls" class="carousel slide p-3" data-ride="carousel">
                <div class="carousel-inner">
                    <?php foreach ($carouselItems as $item): ?>
                    <div class="carousel-item <?php if($item['id'] === '0'){ echo 'active'; }?>">
                        <img src="<?= IMGPATH.$pagename.'/carousel/'.$item['sourcename']; ?>" class="d-block w-100" alt="<?= $item['photoname']; ?>">
                        <div class="carousel-caption">
                            <h1 class="title"><?= $item['photoname']; ?></h1>
                            <h2 class="subtitle"><?= $item['photo_info']; ?></h2>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <?php
        $items = array('sushi' => 'green-machine', 'wraps' => 'curry_flower', 'soepen' => 'chili_mushroom_noodle_soup');
        foreach($items as $item => $image):
    ?>
    <div class="col-12 col-md-6 col-lg-4">
        <div class="card my-2 my-md-3">
            <div class="card-header text-center">
                <?= ucfirst($item); ?>
            </div>
            <img src="<?= IMGPATH.$pagename.'/'.$image; ?>" class="card-img-top" alt="<?= $image; ?>" />
        </div>
    </div>
    <?php
        endforeach;
    ?>
</div>