<head>
    <meta charset="UTC-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9,IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1 minimum-scale=1" />
    <meta name="keywords" content="Beyond Sushi, Sushi, Wraps, Soup, Centrum Castricum, De Castricummer, Heerhugowaard, restaurant, eten, plantaardige producten, platnaardig" />
    <meta name="description" content="Beyond Sushi restaurant en zijn recepten" />
    <meta name="author" content="Rick Blanksma" />
    <meta name="packages" content="
        https://getbootstrap.com/docs/4.4/getting-started/introduction/,
        https://api.jquery.com/,
        https://sass-lang.com/documentation,
        https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself
    "/>

    <title>
        <?= ucwords($pagename) ?> - Beyond Sushi restaurant - Castricum
    </title>

    <link type="image/png" rel="ico" href="<?= IMGPATH ?>favicons/favicon.png" />

    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" />

    <!-- ** PACKAGES ASSETS ** -->
    <!-- jQuery -->
    <script type="application/javascript" src="<?= JSPATH ?>jQuery/jquery-3.4.1.min.js"></script>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="<?= CSSPATH ?>bootstrap.css" />
    <script type="application/javascript" src="<?= JSPATH ?>bootstrap/bootstrap.min.js"></script>

    <!-- Application -->
    <link rel="stylesheet" href="<?= CSSPATH ?>app.min.css" />

</head>