<header>
    <nav class="navbar navbar-expand-md navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="home">Beyond sushi</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-lg-auto ml-md-auto ml-lg-0">
                    <li class="nav-item <?php if($pagename === 'home'){ echo 'active'; }?>">
                        <a class="nav-link" href="home">Home</a>
                    </li>
                    <li class="nav-item dropdown <?php if($pagename === 'sushi' || $pagename === 'wraps_soups'){ echo 'active'; }?>">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Menu
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item <?php if($pagename === 'sushi'){ echo 'active'; } ?>" href="sushi">Sushi</a>
                            <a class="dropdown-item <?php if($pagename === 'wraps_soups'){ echo 'active'; } ?>" href="wraps_soups">Wraps en Soup</a>
                        </div>
                    </li>
                    <li class="nav-item <?php if($pagename === 'contact'){ echo 'active'; }?>">
                        <a class="nav-link" href="contact">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>